pipeline {
  agent any

  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref'],
      [key: 'base_ref', value: '$.base_ref'],
      [key: 'main_repo', value: '$.repository.ssh_url', expressionType: 'JSONPath'],
      [key: 'repo_name', value: '$.repository.name', expressionType: 'JSONPath']
     ],
     causeString: 'Triggered on $ref',
     token: 'project-name',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: false,
     regexpFilterText: '$ref',
     regexpFilterExpression: 'refs/heads/staging'
    )
  }

  stages {
    stage('Preparing source...') {
      steps {
            git branch: 'staging',
            credentialsId: 'tricao',
            url: '$main_repo'
      }
    }

    stage('Building') {
      steps {
        script {
          try {
            telegramSend "😂 Building ${repo_name} - ${ref}..."
            telegramSend "👍 Build Success ${repo_name} - ${ref}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}"
          } catch(e) {
            // mark build as failed
            currentBuild.result = "FAILURE";

            // send slack notification
            telegramSend "💩 Build Failed ${repo_name} - ${ref}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}\nError: ${e}"

            // throw the error
            throw e;
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          try {
            telegramSend "😂 Deploying ${repo_name} - develop..."
            telegramSend "👍 Deploy Success ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}"
          } catch(e) {
            // mark build as failed
            currentBuild.result = "FAILURE";

            // send slack notification
            telegramSend "💩 Build Failed ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}\nError: ${e}"

            // throw the error
            throw e;
          }
        }
      }
    }
  }

  post {
    always {
      deleteDir() // Recursively delete the current directory from the workspace
    }
  }
}