pipeline {
  agent any

  // no base_ref on merge button
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref'],
      [key: 'main_repo', value: '$.repository.ssh_url', expressionType: 'JSONPath'],
      [key: 'repo_name', value: '$.repository.name', expressionType: 'JSONPath']
     ],
     causeString: 'Triggered on $ref',
     token: 'project-name',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: false,
     regexpFilterText: '$ref',
     regexpFilterExpression: 'refs/heads/develop'
    )
  }

  stages {
    stage('Preparing source...') {
      steps {
        git branch: 'develop',
        credentialsId: 'tricao',
        url: '$main_repo'
      }
    }

    stage('Building') {
      steps {
        script {
          try {
            telegramSend "😂 Building ${repo_name} - develop..."
            telegramSend "👍 Build Success ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}"
          } catch(e) {
            // mark build as failed
            currentBuild.result = "FAILURE";

            // send slack notification
            telegramSend "💩 Build Failed ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}\nError: ${e}"

            // throw the error
            throw e;
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          try {
            telegramSend "😂 Deploying ${repo_name} - develop..."
            telegramSend "👍 Deploy Success ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}"
          } catch(e) {
            // mark build as failed
            currentBuild.result = "FAILURE";

            // send slack notification
            telegramSend "💩 Build Failed ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}\nError: ${e}"

            // throw the error
            throw e;
          }
        }
      }
    }

  // stage('Merge staging...') {
  //   steps {
  //     script {
  //       try {
  //         telegramSend "😂 ${repo_name} - Merging develop to staging..."
  //         sshagent(['tricao']) {
  //           sh 'git checkout staging'
  //           sh 'git pull'
  //           sh 'git merge develop'
  //           sh "git push origin staging"
  //         }
  //         telegramSend "👍 Merge Success ${repo_name} - Merge develop to staging: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}"
  //       } catch (e) {
  //         // mark build as failed
  //         currentBuild.result = "FAILURE";

  //         // send slack notification
  //         telegramSend "💩 ${repo_name} - Merge develop to staging Failed ${repo_name} - develop: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'\n${env.BUILD_URL}\nError: ${e}"

  //         // throw the error
  //         throw e;
  //       }
  //     }
  //   }
  // }
  }
}